markdown_extensions:
- attr_list
- md_in_html
- pymdownx.superfences
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    linenums: true
    pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences
nav:
- Tags: Tags.md
- AcquireCameraFocus: AcquireCameraFocus.md
- AcquireInputFocus: AcquireInputFocus.md
- Animation: Animation.md
- AnimationDone: AnimationDone.md
- AnimationInstanceDesc: AnimationInstanceDesc.md
- AnimationSet: AnimationSet.md
- AnimationSetDesc: AnimationSetDesc.md
- AnimationTrack: AnimationTrack.md
- ApplyForce: ApplyForce.md
- Atlas: Atlas.md
- AtlasAnimation: AtlasAnimation.md
- AtlasImage: AtlasImage.md
- Bone: Bone.md
- BufferDesc: BufferDesc.md
- CameraDesc: CameraDesc.md
- ClearColor: ClearColor.md
- CollectionDesc: CollectionDesc.md
- CollectionFactoryDesc: CollectionFactoryDesc.md
- CollectionInstanceDesc: CollectionInstanceDesc.md
- CollectionProxyDesc: CollectionProxyDesc.md
- Collision: Collision.md
- CollisionEvent: CollisionEvent.md
- CollisionObjectDesc: CollisionObjectDesc.md
- CollisionResponse: CollisionResponse.md
- CollisionShape: CollisionShape.md
- ComponenTypeDesc: ComponenTypeDesc.md
- ComponentDesc: ComponentDesc.md
- ComponentPropertyDesc: ComponentPropertyDesc.md
- ContactPoint: ContactPoint.md
- ContactPointEvent: ContactPointEvent.md
- ContactPointResponse: ContactPointResponse.md
- ConvexHull: ConvexHull.md
- ConvexShape: ConvexShape.md
- Create: Create.md
- Cubemap: Cubemap.md
- Cue: Cue.md
- Disable: Disable.md
- DisplayProfile: DisplayProfile.md
- DisplayProfileQualifier: DisplayProfileQualifier.md
- DisplayProfiles: DisplayProfiles.md
- DrawDebugText: DrawDebugText.md
- DrawLine: DrawLine.md
- DrawText: DrawText.md
- EmbeddedComponentDesc: EmbeddedComponentDesc.md
- EmbeddedInstanceDesc: EmbeddedInstanceDesc.md
- Emitter: Emitter.md
- Enable: Enable.md
- EnableGridShapeLayer: EnableGridShapeLayer.md
- EventKey: EventKey.md
- EventTrack: EventTrack.md
- Exit: Exit.md
- FactoryDesc: FactoryDesc.md
- FontDesc: FontDesc.md
- FontMap: FontMap.md
- GamepadMap: GamepadMap.md
- GamepadMapEntry: GamepadMapEntry.md
- GamepadMaps: GamepadMaps.md
- GamepadModifier t: GamepadModifier_t.md
- GamepadTrigger: GamepadTrigger.md
- GlyphBank: GlyphBank.md
- HashDigest: HashDigest.md
- HideApp: HideApp.md
- IK: IK.md
- InputBinding: InputBinding.md
- InstanceDesc: InstanceDesc.md
- InstancePropertyDesc: InstancePropertyDesc.md
- KeyTrigger: KeyTrigger.md
- LabelDesc: LabelDesc.md
- LayoutChanged: LayoutChanged.md
- LightDesc: LightDesc.md
- LuaModule: LuaModule.md
- LuaRef: LuaRef.md
- LuaSource: LuaSource.md
- ManifestData: ManifestData.md
- ManifestFile: ManifestFile.md
- ManifestHeader: ManifestHeader.md
- Material: Material.md
- MaterialDesc: MaterialDesc.md
- Matrix4: Matrix4.md
- Mesh: Mesh.md
- MeshDesc: MeshDesc.md
- MeshSet: MeshSet.md
- Model: Model.md
- ModelAnimationDone: ModelAnimationDone.md
- ModelCancelAnimation: ModelCancelAnimation.md
- ModelDesc: ModelDesc.md
- ModelPlayAnimation: ModelPlayAnimation.md
- Modifier: Modifier.md
- MouseTrigger: MouseTrigger.md
- NodeDesc: NodeDesc.md
- ParticleFX: ParticleFX.md
- PathSettings: PathSettings.md
- PauseSound: PauseSound.md
- PlatformProfile: PlatformProfile.md
- PlayAnimation: PlayAnimation.md
- PlayParticleFX: PlayParticleFX.md
- PlaySound: PlaySound.md
- Point3: Point3.md
- PropertyDeclarationEntry: PropertyDeclarationEntry.md
- PropertyDeclarations: PropertyDeclarations.md
- PropertyDesc: PropertyDesc.md
- PrototypeDesc: PrototypeDesc.md
- Quat: Quat.md
- RayCastMissed: RayCastMissed.md
- RayCastResponse: RayCastResponse.md
- Reboot: Reboot.md
- ReleaseCameraFocus: ReleaseCameraFocus.md
- ReleaseInputFocus: ReleaseInputFocus.md
- Reload: Reload.md
- RenderPrototypeDesc: RenderPrototypeDesc.md
- RequestRayCast: RequestRayCast.md
- RequestVelocity: RequestVelocity.md
- ResetConstant: ResetConstant.md
- ResetConstantParticleFX: ResetConstantParticleFX.md
- ResetConstantTileMap: ResetConstantTileMap.md
- Resize: Resize.md
- ResourceEntry: ResourceEntry.md
- RigAnimation: RigAnimation.md
- RigScene: RigScene.md
- RunScript: RunScript.md
- SceneDesc: SceneDesc.md
- ScriptMessage: ScriptMessage.md
- ScriptUnrefMessage: ScriptUnrefMessage.md
- SetCamera: SetCamera.md
- SetConstant: SetConstant.md
- SetConstantParticleFX: SetConstantParticleFX.md
- SetConstantTileMap: SetConstantTileMap.md
- SetFlipHorizontal: SetFlipHorizontal.md
- SetFlipVertical: SetFlipVertical.md
- SetGain: SetGain.md
- SetGridShapeHull: SetGridShapeHull.md
- SetLight: SetLight.md
- SetPan: SetPan.md
- SetParent: SetParent.md
- SetScale: SetScale.md
- SetSpeed: SetSpeed.md
- SetText: SetText.md
- SetTexture: SetTexture.md
- SetTimeStep: SetTimeStep.md
- SetUpdateFrequency: SetUpdateFrequency.md
- SetViewProjection: SetViewProjection.md
- SetVsync: SetVsync.md
- ShaderDesc: ShaderDesc.md
- Skeleton: Skeleton.md
- SoundDesc: SoundDesc.md
- SoundEvent: SoundEvent.md
- SplinePoint: SplinePoint.md
- SpriteDesc: SpriteDesc.md
- SpriteGeometry: SpriteGeometry.md
- SpriteTexture: SpriteTexture.md
- StartRecord: StartRecord.md
- StopParticleFX: StopParticleFX.md
- StopRecord: StopRecord.md
- StopSound: StopSound.md
- StreamDesc: StreamDesc.md
- TextTrigger: TextTrigger.md
- Texture: Texture.md
- TextureFormatAlternative: TextureFormatAlternative.md
- TextureImage: TextureImage.md
- TextureProfile: TextureProfile.md
- TextureProfiles: TextureProfiles.md
- TextureSet: TextureSet.md
- TextureSetAnimation: TextureSetAnimation.md
- TileCell: TileCell.md
- TileGrid: TileGrid.md
- TileLayer: TileLayer.md
- TileSet: TileSet.md
- TogglePhysicsDebug: TogglePhysicsDebug.md
- ToggleProfile: ToggleProfile.md
- TouchTrigger: TouchTrigger.md
- Transform: Transform.md
- Trigger: Trigger.md
- TriggerEvent: TriggerEvent.md
- TriggerResponse: TriggerResponse.md
- Vector3: Vector3.md
- Vector3One: Vector3One.md
- Vector4: Vector4.md
- Vector4One: Vector4One.md
- Vector4WOne: Vector4WOne.md
- VelocityResponse: VelocityResponse.md
- VertexAttribute: VertexAttribute.md
- WindowResized: WindowResized.md
- index: index.md
plugins:
- tags:
    listings_map:
      scoped:
        scope: true
    listings_sort_by: '!!python/name:material.plugins.tags.item_url'
    listings_sort_reverse: true
    tags_file: Tags.md
- search:
    pipeline:
    - stemmer
    - stopWordFilter
    - trimmer
site_name: PyDefold Documenetation
theme:
  features:
  - search.share
  - content.code.copy
  - content.code.select
  name: material
  palette:
  - scheme: default
    toggle:
      icon: material/brightness-7
      name: Switch to light mode
